apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-gzkqrf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-gzkqrf
    app.kubernetes.io/part-of: jvm-build-suite-application-fhwf
  name: jvm-build-suite-component-gzkqrf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-gzkqrf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-gzkqrf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-unlq-tenant/jvm-build-suite-application-fhwf/jvm-build-suite-component-gzkqrf@sha256:50c1ed65075f2d7f3ef674ee73a708a7a6a7fa9b34445af866f45c2378c31a86
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
